### ISSUE TITLE
Random reboot after upgrade

### ISSUE THREAD

**Issue by ljcljc** [Hexxeh/rpi-update#167] opened 2015-03-20 11:16 UTC
I run 'rpi-update' to update kernel to the latest version, and now it won't be dead, but it would reboot for no reason.

After about 2 hours, pi would automatically reboot as I see in /var/log/syslog

Mar 20 15:45:48 205-1-1 /USR/SBIN/CRON[4215]: (CRON) info (No MTA installed, discarding output)
Mar 20 15:46:36 205-1-1 shutdown[4310]: shutting down for system reboot
Mar 20 15:46:36 205-1-1 init: Switching to runlevel: 6
Mar 20 15:46:39 205-1-1 mysqld: 150320 15:46:39 [Note] /usr/sbin/mysqld: Normal shutdown
Mar 20 15:46:39 205-1-1 mysqld:
Mar 20 15:46:39 205-1-1 mysqld: 150320 15:46:39 [Note] Event Scheduler: Purging the queue. 0 events
Mar 20 15:46:39 205-1-1 mysqld: 150320 15:46:39 InnoDB: Starting shutdown...
Mar 20 15:46:41 205-1-1 mysqld: 150320 15:46:41 InnoDB: Shutdown completed; log sequence number 718843536
Mar 20 15:46:41 205-1-1 mysqld: 150320 15:46:41 [Note] /usr/sbin/mysqld: Shutdown complete
Mar 20 15:46:41 205-1-1 mysqld:
Mar 20 15:46:42 205-1-1 mysqld_safe: mysqld from pid file /var/run/mysqld/mysqld.pid ended
Mar 20 15:46:47 205-1-1 kernel: imklog 5.8.11, log source = /proc/kmsg started.
Mar 20 15:46:47 205-1-1 rsyslogd: [origin software="rsyslogd" swVersion="5.8.11" x-pid="2010" x-info="http://www.rsyslog.com"] start
Mar 20 15:46:47 205-1-1 kernel: [ 0.000000] Booting Linux on physical CPU 0xf00
Mar 20 15:46:47 205-1-1 kernel: [ 0.000000] Initializing cgroup subsys cpu
Mar 20 15:46:47 205-1-1 kernel: [ 0.000000] Initializing cgroup subsys cpuacct

My pi is working perfectly for several months on rpi b+, and has problems after I upgrade. I believe it's a problem with kernel. Can someone help me with that? Thanks

**Comment by popcornmix** [comment] 2015-03-20 13:08
Duplicate of https://github.com/Hexxeh/rpi-update/issues/168

**Closed by popcornmix** 2015-03-20 13:08 UTC
