### ISSUE TITLE
Failed to down update for rpi-update

### ISSUE THREAD

**Issue by stayupthetree** [Hexxeh/rpi-update#206] opened 2016-05-15 18:11 UTC
' !!! Failed to download update for rpi-update!
 !!! Make sure you have ca-certificates installed and that the time is set correctly

I have read the readme. I made sure ca-certificates was installed, even did a dpkg reconfigure.
Made sure time was correct with the ntpupdate.

Tried alternative steps cloning the repo. Same SSL Cert error.

-k and --insecure did nothing to prevent it

**Comment by stayupthetree** [comment] 2016-05-15 18:20
I was able to make some progress by editing rpi-update and adding -k to every curl command. Then I realized when I ran rpi-update it overwrote my changes.

I then discovered this gem 'sudo UPDATE_SELF=0 ./rpi-update'

Seems to be running fine currently.

**Comment by Ruffio** [comment] 2016-05-20 08:58
@stayupthetree I just ran the rpi-update without issues on a clean Raspbian image without installing any certificates or dpkg reconfigure. What is your setup? Could you try with a clean image?

**Comment by sanelson2000** [comment] 2016-05-28 03:40
I'm having the same issue, on a Raspberry Pi 3 with Jessie kernel version 4.4.11-v7+.  I'm using the RetroPie image.  I noticed that rpi-update wasn't even installed, installed it myself, and found it not working.

**Comment by Ruffio** [comment] 2016-07-03 21:09
I just installed Rasbian and Lite and har no problems  at all. Could you check the time and CA certificates?

**Comment by rillian** [comment] 2016-07-05 22:10
I think this is an issue with the `curl` package on the retropie and/or rasbian jessie images. I have the same problem, and a generic `curl --head https://github.com/` fails with a certificate validation error.

Meanwhile `curl --cacert /etc/ssl/certs/ca-certificates.crt --head https://github.com/` succeeds, so there's something wrong with the default curl path.

Using the corresponding environment variable I can work around the issue
```sh
sudo CURL_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt rpi-update
```
```

**Comment by popcornmix** [comment] 2016-07-06 14:05
@rillian can you confirm that you have this issue with a clean raspbian jessie image?
It certainly works fine for me.

**Comment by Ruffio** [comment] 2016-08-01 13:48
@rillian is this still an issue? Have you tried with a clean Raspbian Jessie image? I can't recreate your issue.

**Comment by KevinBEvv** [comment] 2016-10-03 15:43
I found that I was having trouble with DNS, which was caused by a firewall restriction (not apart of the RaspPi Raspbian install, but a separate issue).  This caused the error for me.

**Comment by Ruffio** [comment] 2017-01-22 16:47
@stayupthetree is this still an issue? If not, please close it. Thanks.

**Comment by seyyah** [comment] 2017-04-06 06:17
I have this issue with my ~~clean~~ raspbian jessie image.

```sh
$ sudo apt-get update
$ sudo apt-get upgrade

$ lsb_release -a
No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 8.0 (jessie)
Release:        8.0
Codename:       jessie

$ uname -a
Linux raspberrypi 4.4.50-v7+ #970 SMP Mon Feb 20 19:18:29 GMT 2017 armv7l GNU/Linux

$ sudo rpi-update -k
 *** Raspberry Pi firmware updater by Hexxeh, enhanced by AndrewS and Dom
 *** Performing self-update
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: http://curl.haxx.se/docs/sslcerts.html

 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
 !!! Failed to download update for rpi-update!
 !!! Make sure you have ca-certificates installed and that the time is set correctly

$ sudo CURL_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt rpi-update
 *** Raspberry Pi firmware updater by Hexxeh, enhanced by AndrewS and Dom
 *** Performing self-update
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 12762  100 12762    0     0  20237      0 --:--:-- --:--:-- --:--:-- 20225
 *** Relaunching after update
 *** Raspberry Pi firmware updater by Hexxeh, enhanced by AndrewS and Dom
 *** We're running for the first time
 *** Backing up files (this will take a few minutes)
 *** Remove old firmware backup
 *** Backing up firmware
 *** Remove old modules backup
 *** Backing up modules 4.4.50-v7+
#############################################################
WARNING: This update bumps to rpi-4.9.y linux tree
Be aware there could be compatibility issues with some drivers
Discussion here:
https://www.raspberrypi.org/forums/viewtopic.php?f=29&t=167934
##############################################################
Would you like to proceed? (y/N)
 *** Downloading specific firmware revision (this will take a few minutes)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   168    0   168    0     0    232      0 --:--:-- --:--:-- --:--:--   232
100 53.7M  100 53.7M    0     0   507k      0  0:01:48  0:01:48 --:--:--  866k
 *** Updating firmware
 *** Updating kernel modules
 *** depmod 4.9.20+
 *** depmod 4.9.20-v7+
 *** Updating VideoCore libraries
 *** Using HardFP libraries
 *** Updating SDK
 *** Running ldconfig
 *** Storing current firmware revision
 *** Deleting downloaded files
 *** Syncing changes to disk
 *** If no errors appeared, your firmware was successfully updated to 3ff94f1fc459f88d3e2530542fb609643a7bd1a6
 *** A reboot is needed to activate the new firmware
```

**Comment by popcornmix** [comment] 2017-04-06 09:59
@seyyah does ``date`` report the correct date/time?

**Comment by seyyah** [comment] 2017-04-06 11:13
I configure date with `dpkg-reconfigure tzdata # Asia -> Istanbul` before `sudo rpi-update` OR `sudo rpi-update -k`. So,

```sh
$ sudo dpkg-reconfigure tzdata

$ sudo rpi-update
...
!!! Make sure you have ca-certificates installed and that the time is set correctly

$ sudo rpi-update -k
...
!!! Make sure you have ca-certificates installed and that the time is set correctly

$ sudo CURL_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt rpi-update
...
 *** A reboot is needed to activate the new firmware
```

**Comment by popcornmix** [comment] 2017-04-06 14:41
But does ``date`` report the correct date and time?

**Comment by seyyah** [comment] 2017-04-06 14:54
Yes, `date` report the correct/locale date and time,

```sh
$ LC_ALL=C date -u; \
LC_ALL=C TZ="America/Los_Angeles" date; \
LC_ALL=C TZ="Asia/Istanbul" date; \
LC_ALL=C date
Thu Apr  6 14:53:23 UTC 2017
Thu Apr  6 07:53:23 PDT 2017
Thu Apr  6 17:53:23 +03 2017 <-- local date and time and it is correct
Thu Apr  6 17:53:23 +03 2017
```

**Comment by popcornmix** [comment] 2017-04-06 15:01
If you run
```
curl -Lfs --output /tmp/rpi-update https://raw.githubusercontent.com/Hexxeh/rpi-update/master/rpi-update
```
do you get the same error?

**Comment by seyyah** [comment] 2017-04-06 18:59
I will try and report as soon as possible.

**Comment by seyyah** [comment] 2017-04-11 05:24
I get below the same error,

```sh
$ curl -Lfs --output /tmp/rpi-update https://raw.githubusercontent.com/Hexxeh/rpi-update/master/rpi-update

<not write anything on the screen>

$ cat /tmp/rpi-update
cat: /tmp/rpi-update: No such file or directory

$ curl https://raw.githubusercontent.com/Hexxeh/rpi-update/master/rpi-update
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.

$ curl -k https://raw.githubusercontent.com/Hexxeh/rpi-update/master/rpi-update
#!/bin/bash

set -o nounset
set -o errexit

REPO_URI=${REPO_URI:-"https://github.com/Hexxeh/rpi-firmware"}
...
```

**Comment by Ruffio** [comment] 2017-05-16 04:41
@stayupthetree can this issue be closed?

**Comment by hgovindarajan** [comment] 2017-08-12 18:46
I ran into this issue when I attempted to setup & update my rasp-pi prior to configuring my wifi adapter. Doh!

**Comment by popcornmix** [comment] 2017-08-13 11:38
No response from OP so closing. Feel free to reopen if there is new information.

**Closed by popcornmix** 2017-08-13 11:38 UTC

**Comment by amrithmmh** [comment] 2018-03-26 12:19
i am getting this error now after updating and upgrading to stretch

**Comment by zimtzeke** [comment] 2018-10-24 00:49
for me this worked fine:
$ sudo CURL_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt rpi-update

**Comment by orjanv** [comment] 2019-03-21 13:02
Getting this error in jessie, tried the above with no luck.

**Comment by simonliu009** [comment] 2020-03-18 11:25
I accidently  typed "N" after `Would you like to proceed? (y/N)` and I got the same error when I tried to run `sudo rpi-update`again.  `date` command returned the correct time. I tried removing and reinstalling `ca-certificates` and no luck.  Then I walked out for around 40 minutes and tried again when I came back , everything works fine now.

**Comment by zhangyoufu** [comment] 2020-11-07 05:13
FYI, `raw.githubusercontent.com` is blocked in mainland China.

`sudo UPDATE_SELF=0 rpi-update` to skip self update or edit `/etc/hosts` manually to workaround DNS pollution.

**Comment by vizshrc** [comment] 2020-11-22 09:08
> FYI, `raw.githubusercontent.com` is blocked in mainland China.
> 
> `sudo UPDATE_SELF=0 rpi-update` to skip self update or edit `/etc/hosts` manually to workaround DNS pollution.

Right

**Comment by arvinxian** [comment] 2021-01-19 05:44
> FYI, `raw.githubusercontent.com` is blocked in mainland China.
> 
> `sudo UPDATE_SELF=0 rpi-update` to skip self update or edit `/etc/hosts` manually to workaround DNS pollution.

it works, in mainland China

**Comment by geerlingguy** [comment] 2022-07-06 15:50
Just wanted to mention I got this error on a fresh install of Pi OS lite 64-bit from 04-04-2022, after running apt dist-upgrade and rebooting. I ran it with `UPDATE_SELF=0` and rebooted, then ran it again without `UPDATE_SELF=0` and it worked. Might've also worked if I found a way to get certs updated separately, not sure...

**Comment by popcornmix** [comment] 2022-07-07 10:32
@geerlingguy if you are currently seeing this issue, then report output of:
```
date
curl -Lfs --output /tmp/rpi-update https://raw.githubusercontent.com/raspberrypi/rpi-update/master/rpi-update
```

**Comment by 652436962** [comment] 2022-07-12 09:44
> FYI, `raw.githubusercontent.com` is blocked in mainland China.
> 
> `sudo UPDATE_SELF=0 rpi-update` to skip self update or edit `/etc/hosts` manually to workaround DNS pollution.

can you provide your email  ?   I  can't come true

**Comment by 652436962** [comment] 2022-07-13 00:51
> > 仅供参考，`raw.githubusercontent.com`在中国大陆被封锁。
> > `sudo UPDATE_SELF=0 rpi-update`跳过自我更新或`/etc/hosts`手动编辑以解决 DNS 污染问题。
> 
> 有效，在中国大陆

are  you update  sucess ?   what  you  do?   can you provide  your email?

**Comment by hegdenischay** [comment] 2023-09-02 01:44
FYI for the Indians looking at this issue, the ISP [Jio](https://www.jio.com/) blocks `raw.githubusercontent.com` for some reason. Changing the DNS to anything other than the ISP's DNS fixes this issue.

**Comment by krishnaTORQUE** [comment] 2023-09-02 07:43
> 

Might not true.
Because I am using airtel fiber.

**Comment by hegdenischay** [comment] 2023-09-02 08:40
@krishnaTORQUE This is not an India-wide problem, this is specifically a Reliance Jio problem. They're far too trigger happy in blocking websites, and I haven't had this problem on other ISPs.

**Comment by krishnaTORQUE** [comment] 2023-09-02 08:42
> @krishnaTORQUE This is not an India-wide problem, this is specifically a Reliance Jio problem. They're far too trigger happy in blocking websites, and I haven't had this problem on other ISPs.

Yes I got it.
But I am facing the same issue but I am using airtel fiber.
If jio the only provider blocking then I should not face this issue but I do face.
