### ISSUE TITLE
[New Feature Request]  Auto Reboot On Upgrade

### ISSUE THREAD

**Issue by tundratim** [Hexxeh/rpi-update#186] opened 2015-07-28 22:42 UTC
Again, in the spirit of supporting automated workflows, it would be nice to have an option to kick off a reboot automatically if the firmware gets upgraded.

**Comment by popcornmix** [comment] 2015-07-29 14:22
Anything wrong with:
```sudo rpi-update && sudo reboot```

**Comment by tundra-git** [comment] 2015-07-29 17:04
Does rpi-update set the error level such that this would not reboot if there were no firmware update?

**Comment by tundra-git** [comment] 2015-07-29 19:36
I just checked:  rpi-update always sets exit code to 0 regardless of whether there was a firmware update or not, so the above solution will ALWAYS reboot.  What I want is reboot only if there has been a firmware update.

**Comment by Ruffio** [comment] 2016-04-30 07:00
Duplicate of https://github.com/Hexxeh/rpi-update/issues/157 ?

**Comment by tundratim** [comment] 2016-04-30 16:45
Yes, they appear to be essentially identical issues.

**Closed** 2016-11-22 19:43 UTC
