### ISSUE TITLE
OC on the GPU not working

### ISSUE THREAD

**Issue by himuura** [Hexxeh/rpi-update#289] opened 2019-11-28 17:45 UTC
Don't quite know if this is an issue but someone might have the same problem. Used to have arm_freq=2000 and over_voltage=4. Updated the firmware today and the software packages as well (mesa drivers where updated as i can see). The thing is, to try out the new drivers and stability i added the gpu_freq=650. Rebooted and nothing, black screen. Changed to 600, black screen. Over_voltage set to 6, still nothing. Tested the 550 option as well with both 4 and 6 over voltage and i have SSH access but no image after POST. So, my question is, GPU is no longer overclockable? Thanks in advance!

PS - PSU from que RPi foundation, the recommended one. And RPI 4 4Gb!!

**Comment by popcornmix** [comment] 2019-11-29 15:51
duplicate of https://github.com/raspberrypi/firmware/issues/1290

**Closed by popcornmix** 2019-11-29 15:51 UTC
