### ISSUE TITLE
Panic VFS after update

### ISSUE THREAD

**Issue by matthuisman** [Hexxeh/rpi-update#166] opened 2015-03-20 01:56 UTC
Using stock NOOBS
Boot into Raspbian.
Run sudo rpi-udapte
Updates successfully and says reboot.
Reboot.

Message "PANIC: VFS: Unable to mount root fs on unknown-lock(179,2)

This is the 2nd SD card I have tried.
Using very good power supply with thick DC cables. Only ethernet and keyboard plugged in.

It also "kills" NOOBS. Can't hold shift to get into NOOBS anymore. Straight into Raspbian boot then panic.

Almost like NOOBS has been corrupted by the rpi-update

**Comment by matthuisman** [comment] 2015-03-20 02:12
Have posted an issue on RPI firmware with more details here:
https://github.com/raspberrypi/firmware/issues/398

**Comment by popcornmix** [comment] 2015-03-20 13:19
Duplicate of raspberrypi/firmware#398

**Closed by popcornmix** 2015-03-20 13:19 UTC
