### ISSUE TITLE
Rate Limit exceeded

### ISSUE THREAD

**Issue by Jamesking56** [Hexxeh/rpi-update#151] opened 2014-09-30 16:22 UTC
Hello,

GitHub has a rate limit in place for API requests. When I do rpi-update it says I have hit this limit.

```
 *** Raspberry Pi firmware updater by Hexxeh, enhanced by AndrewS and Dom
 *** Performing self-update
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7635  100  7635    0     0  20220      0 --:--:-- --:--:-- --:--:-- 26058
 *** Relaunching after update
 *** Raspberry Pi firmware updater by Hexxeh, enhanced by AndrewS and Dom
 *** No hash received from github: https://api.github.com/repos/Hexxeh/rpi-firmware/git/refs/heads/master
{
  "message": "API rate limit exceeded for X.X.X.X. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
  "documentation_url": "https://developer.github.com/v3/#rate-limiting"
}
```

**Comment by peteforde** [comment] 2015-03-19 19:34
I'm getting slammed by this as well. I have 60+ RasPis here and trying to run rpi-update just exploded everything. I wish there was a way to pass in a user token as @Jamesking56 suggested.

**Comment by popcornmix** [comment] 2015-03-20 13:21
Feel free to create a pull request to support a personal access token.

**Comment by fenhl** [comment] 2016-12-04 00:44
Why was this closed? I just ran into this issue.

**Comment by peteforde** [comment] 2016-12-04 01:23
@fenhl I think @Jamesking56 closed it with a #donthavetimebutknockyourselfout and that's completely within his right. Supporting a project like this is often thankless. Please do investigate, as they say!

What I ended up doing was a combination of hosting my own update blobs on Dropbox and reconsidering my approach to deploying a fix in general.

First, you probably don't randomly need to update your Pis unless you need a device that isn't currently supported by an older version of Linux. It's definitely not something to do without consideration.

However, the main change I made is that I adopted a process that is roughly:

1. Update a script that I verify can build a brand new Pi image from scratch
2. Run the script and put the image on a 4GB card
3. Use a duplicator to copy to 15 8GB cards

We used to use a nasty assortment of USB readers to do duplication. This is a reasonable strategy until it isn't. Yes, duplicators seem expensive but if your time is worth >$100/hour then they pay for themselves VERY quickly. YMMV.

Why do I copy to 8GB cards you must be wondering? Well, every batch of SD cards has a slightly different number of bytes available for writing - sometimes it's 10's of bytes, often it's 10-15MB. The price of a 8GB compared to a 4GB card is negligible so I'm fine with paying pennies extra for a 100% guarantee that the 8GB won't fill up before it's finished writing an image.

**Comment by fenhl** [comment] 2016-12-04 01:33
I'm not sure I understand what you're talking about. I was simply following a tutorial (for installing [`info-beamer-pi`](https://info-beamer.com/pi)) which instructed me to run `rpi-update`.

**Comment by peteforde** [comment] 2016-12-04 01:39
Fair enough. Just recognize that you're also someone who hasn't contributed to the project showing up to a long-dead thread upset that GitHub is rate limiting you.

You really shouldn't be having this problem unless you're hammering GitHub. How many Pis are you trying to update at once?

**Comment by fenhl** [comment] 2016-12-04 02:18
I'm not upset, was just trying to figure out what's going on. And I'm just working with a single Pi.

Apparently the issue was caused by a [BitBar](https://github.com/matryer/bitbar) plugin which pulls GitHub notifications every 30 seconds, which was running on a different computer in the same LAN. Even though this plugin was using an access token to authenticate to the GitHub API, temporarily disabling it and waiting until the rate limit state reset allowed me to run `rpi-update` without any issues.

**Comment by Jamesking56** [comment] 2016-12-04 07:53
I closed the issue because after waiting 24 hours it never came back for me. I am only using 1 pi so I rarely hit the rate limit.

**Comment by popcornmix** [comment] 2016-12-04 16:57
I think this can be closed.
Github has API rate limits which are far higher than you would hit from normal use of rpi-update.
If you are making a large numbers of git API calls for other uses or and running rpi-update very frequently then you will have to slow down until github is happy with your usage.

**Comment by Ruffio** [comment] 2017-01-22 16:48
@Jamesking56 can this issue be closed?

**Comment by Jamesking56** [comment] 2017-01-22 22:00
Ask @fenhl they wanted it to be reopened.

**Comment by fenhl** [comment] 2017-01-22 22:03
I don't think the issue is fixed until a personal access token can be provided.

**Comment by darkwinternight** [comment] 2017-03-14 13:18
I agree, it should be possible to provide an access token. The change required should be trivial. If no one else will do it, I can.

**Comment by popcornmix** [comment] 2017-03-14 15:45
@darkwinternight Feel free to submit a pull request that allows an access token to be specified.

**Comment by darkwinternight** [comment] 2017-03-15 09:55
@popcornmix I created a pull request for this: https://github.com/Hexxeh/rpi-update/pull/237

**Closed** 2017-03-15 14:16 UTC

**Comment by darkwinternight** [comment] 2017-03-15 14:19
Actually, just as a follow-up information, I hit the rate limit at work constantly since we work with GitHub a lot (web development).
